const RAW = window.OVERUNDER_DATA;
let DATA;
try {
  const local = localStorage.getItem('overunder_data_override');
  DATA = local ? JSON.parse(local) : structuredClone(RAW);
} catch(e) { DATA = structuredClone(RAW); }
const $ = s => document.querySelector(s);
const teamMap = () => Object.fromEntries(DATA.teams.map(t=>[t.id,t]));
const nameOf = id => teamMap()[id]?.name || 'TBD';
const fmt = n => new Intl.NumberFormat('sr-RS').format(Number(n||0));
const route = () => (location.hash.replace('#/','') || 'home').split('?')[0];
const bgMap = {home:'home-bg.png',league:'league-bg.png',cup:'cup-bg.png',double:'double-bg.png',budget:'budget-bg.png',record:'record-bg.png',rules:'rules-bg.png'};
function shell(content,active){
  const items=[['home','POČETNA'],['league','LIGA'],['cup','KUP'],['double','DUPLO KOLO'],['budget','BUDŽET'],['record','NAJVIŠE POENA'],['rules','PRAVILA & NAGRADE']];
  return `<div class="app-shell"><div class="bg" style="background-image:url('assets/${bgMap[active]||bgMap.home}')"></div><header class="topbar"><div class="container nav"><a class="brand" href="#/home"><img src="assets/logo.png" alt="OverUnder logo"><span class="brand-text">OVER UNDER</span></a><nav class="menu" id="menu">${items.map(([r,l])=>`<a class="${r===active?'active':''}" href="#/${r}">${l}</a>`).join('')}</nav><button class="hamb" id="hamb">☰</button></div></header><main class="container">${content}</main><footer class="footer"><div class="container"><b>OVER UNDER</b> · EuroLeague Fantasy · ${DATA.meta.season}</div></footer><a class="admin-link" href="admin.html" title="Edit podataka">⚙</a></div>`;
}
function initNav(){const h=$('#hamb'),m=$('#menu');if(h)h.onclick=()=>m.classList.toggle('open');document.querySelectorAll('.menu a').forEach(a=>a.onclick=()=>m?.classList.remove('open'));}
function home(){const cards=[['league','LIGA','Završnih 6 kola · poslednjih 10 timova'],['cup','OVERUNDER KUP','18 timova · prvi do 3 pobede'],['budget','BUDŽET','Uplate, dugovanja i status'],['double','DUPLO KOLO','Pet najnižih zbirnih rezultata'],['record','NAJVIŠE POENA','Automatski rekord sezone'],['rules','PRAVILA & NAGRADE','Pravila, penali i nagrade']];return shell(`<section class="hero"><div class="eyebrow">EUROLEAGUE FANTASY · ${DATA.meta.season}</div><h1>THE GAME IS <span class="gold">BACK.</span></h1><div class="accent-line"></div><div class="sub">Privatna EuroLeague Fantasy liga.<br>Jedna sezona. 38 kola. Jedan šampion.</div></section><section class="grid home-grid">${cards.map(([r,t,p])=>`<a class="card nav-card" href="#/${r}"><div><h3>${t}</h3><p>${p}</p></div><span class="go">→</span></a>`).join('')}</section>`,'home');}
function leagueRows(){return DATA.league.participants.map((p,i)=>{const total=DATA.league.rounds.reduce((s,r)=>s+(Number(p.scores[r])||0),0);return {...p,total,seed:i}}).sort((a,b)=>b.total-a.total||a.seed-b.seed)}
function league(){const rows=leagueRows();const desktop=`<div class="table-wrap desktop-table"><table><thead><tr><th>POS.</th><th>NAZIV TIMA</th>${DATA.league.rounds.map(r=>`<th>R${r}</th>`).join('')}<th>UKUPNO</th></tr></thead><tbody>${rows.map((p,i)=>`<tr><td class="rank">${i+1}</td><td class="team">${nameOf(p.teamId)}</td>${DATA.league.rounds.map(r=>`<td><span class="score-pill">${p.scores[r]??'–'}</span></td>`).join('')}<td><b>${p.total.toFixed(1).replace('.0','')}</b></td></tr>`).join('')}</tbody></table></div>`;const mobile=`<div class="mobile-list">${rows.map((p,i)=>`<div class="card team-card"><div class="row"><strong>#${i+1} ${nameOf(p.teamId)}</strong><b style="color:var(--gold2)">${p.total.toFixed(1).replace('.0','')} pts</b></div><div class="rounds">${DATA.league.rounds.map(r=>`<div class="mini"><span>R${r}</span><b>${p.scores[r]??'–'}</b></div>`).join('')}</div></div>`).join('')}</div>`;return shell(`<section class="page-head"><h1>LIGA</h1><p>Završnih 6 kola · poslednjih 10 ekipa · R33–R38</p></section><section class="grid stats"><div class="card stat"><small>Učesnici</small><b>10</b></div><div class="card stat"><small>Kola</small><b>6</b></div><div class="card stat"><small>Start</small><b>R33</b></div><div class="card stat"><small>Kraj</small><b>R38</b></div></section>${desktop}${mobile}`,'league');}
function allCupMatches(){return [...DATA.cup.prelim,...DATA.cup.r16,...DATA.cup.quarters,...DATA.cup.semis,...DATA.cup.final]}
function findMatch(id){return allCupMatches().find(m=>m.id===id)}
function resolveTeamRef(ref){if(typeof ref==='string')return ref;if(ref&&ref.winnerOf)return winnerOf(ref.winnerOf);return null}
function winnerOf(id){const m=findMatch(id);if(!m)return null;if(Number(m.winsA)>=DATA.cup.winsNeeded)return resolveTeamRef(m.teamA);if(Number(m.winsB)>=DATA.cup.winsNeeded)return resolveTeamRef(m.teamB);return null}
function matchCard(m,label){const a=resolveTeamRef(m.teamA),b=resolveTeamRef(m.teamB),wa=Number(m.winsA)||0,wb=Number(m.winsB)||0,aw=wa>=DATA.cup.winsNeeded,bw=wb>=DATA.cup.winsNeeded;return `<div class="match"><div style="font-size:11px;color:#999;margin-bottom:5px">${label||m.id.toUpperCase()}</div><div class="teamline ${aw?'winner':''}"><span class="name">${a?nameOf(a):'TBD'}</span><span class="result">${wa}:${wb}</span></div><div class="teamline ${bw?'winner':''}"><span class="name">${b?nameOf(b):'TBD'}</span><span class="result">${wb}:${wa}</span></div></div>`}
function cup(){const rounds=[['PRELIMINARNA',DATA.cup.prelim],['ROUND OF 16',DATA.cup.r16],['ČETVRTFINALE',DATA.cup.quarters],['POLUFINALE',DATA.cup.semis],['FINALE',DATA.cup.final]],champ=winnerOf('f1');return shell(`<section class="page-head"><h1>OVERUNDER KUP</h1><p>18 učesnika · prvi do 3 pobede · trenutni rezultat se prikazuje automatski</p></section><section class="grid stats"><div class="card stat"><small>Učesnici</small><b>18</b></div><div class="card stat"><small>Format</small><b>BEST OF 5</b></div><div class="card stat"><small>Za prolaz</small><b>3 POBEDE</b></div><div class="card stat"><small>Početak</small><b>${DATA.meta.cupStartText}</b></div></section><div class="cup-columns">${rounds.map(([t,ms])=>`<section class="cup-round"><h3>${t}</h3>${ms.map((m,i)=>matchCard(m,`${t} ${i+1}`)).join('')}</section>`).join('')}</div><div class="card record-hero" style="margin-top:16px"><div class="eyebrow">CHAMPION</div><h2>${champ?nameOf(champ):'TBD'}</h2></div>`,'cup');}
function budgetRows(){return DATA.budget.map((b,i)=>{const total=(Number(b.participation)||0)+(Number(b.league)||0),paid=Number(b.paid)||0,outstanding=Math.max(0,total-paid),status=outstanding===0?'paid':paid>0?'partial':'owes';return {...b,total,paid,outstanding,status,seed:i}})}
function budget(){const rows=budgetRows(),collected=rows.reduce((s,r)=>s+r.paid,0),out=rows.reduce((s,r)=>s+r.outstanding,0);const tr=rows.map((r,i)=>`<tr><td>${i+1}</td><td class="team">${nameOf(r.teamId)}</td><td>${fmt(r.participation)}</td><td>${fmt(r.league)}</td><td><b>${fmt(r.total)}</b></td><td><span class="status ${r.status}">${r.status==='paid'?'PLAĆENO':r.status==='partial'?'DELIMIČNO':'DUGUJE'} · ${fmt(r.outstanding)} RSD</span></td></tr>`).join('');return shell(`<section class="page-head"><h1>BUDŽET</h1><p>Pregled uplata, dugovanja i stanja</p></section><section class="grid stats"><div class="card stat"><small>Učesnici</small><b>${rows.length}</b></div><div class="card stat"><small>Naplaćeno</small><b>${fmt(collected)} RSD</b></div><div class="card stat"><small>Dugovanje</small><b>${fmt(out)} RSD</b></div><div class="card stat"><small>Kotizacija</small><b>${fmt(DATA.meta.entryFee)} RSD</b></div></section><div class="table-wrap"><table><thead><tr><th>#</th><th>NAZIV TIMA</th><th>UČEŠĆE</th><th>LIGA</th><th>UKUPNO</th><th>STATUS</th></tr></thead><tbody>${tr}</tbody></table></div>`,'budget');}
function doublePage(){const d=DATA.doubleRounds[DATA.doubleRounds.length-1],entries=d.entries.map(e=>({...e,total:(Number(e.scoreA)||0)+(Number(e.scoreB)||0)})).sort((a,b)=>a.total-b.total).slice(0,5);return shell(`<section class="page-head"><h1>DUPLO KOLO</h1><p>Dva kola. Jedan zbir. Prikaz pet najnižih rezultata.</p></section><section class="grid stats"><div class="card stat"><small>Format</small><b>2 KOLA</b></div><div class="card stat"><small>Broj timova</small><b>5</b></div><div class="card stat"><small>Penal</small><b>${fmt(DATA.meta.doublePenalty)} RSD</b></div><div class="card stat"><small>Aktuelno</small><b>${d.label}</b></div></section><div class="table-wrap"><table><thead><tr><th>POS.</th><th>NAZIV TIMA</th><th>KOLO ${d.roundA}</th><th>KOLO ${d.roundB}</th><th>UKUPNO</th><th>PENAL</th></tr></thead><tbody>${entries.map((e,i)=>`<tr><td class="rank">${i+1}</td><td class="team">${nameOf(e.teamId)}</td><td>${e.scoreA}</td><td>${e.scoreB}</td><td><b>${e.total}</b></td><td>${fmt(DATA.meta.doublePenalty)} RSD</td></tr>`).join('')}</tbody></table></div>`,'double');}
function record(){const history=[...DATA.highScores].sort((a,b)=>b.points-a.points),rec=history[0]||null;return shell(`<section class="page-head"><h1>NAJVIŠE POENA</h1><p>Rekord sezone ${DATA.meta.season}</p></section><div class="card record-hero"><div class="eyebrow">SEZONSKI REKORD</div><div class="pts">${rec?rec.points:'000'}</div><h2>${rec?nameOf(rec.teamId):'TEAM 01'}</h2><p>${rec?`KOLO ${rec.round}`:'KOLO 00'}</p></div><div class="card history"><h3 style="font-family:'Bebas Neue';font-size:30px;color:var(--gold2);margin-top:0">ISTORIJA REKORDA</h3>${history.length?`<div class="table-wrap"><table><thead><tr><th>#</th><th>TIM</th><th>KOLO</th><th>POENI</th></tr></thead><tbody>${history.map((h,i)=>`<tr><td>${i+1}</td><td class="team">${nameOf(h.teamId)}</td><td>${h.round}</td><td><b>${h.points}</b></td></tr>`).join('')}</tbody></table></div>`:`<div class="notice">Još nema unetih rezultata. Rekord će se pojaviti automatski čim dodaš prvi rezultat.</div>`}</div>`,'record');}
function rules(){const blocks=[['UČESTVOVANJE',DATA.rules.participation],['PENALI',DATA.rules.penalties],['LIGA',DATA.rules.leagueFinal],['KUP',DATA.rules.cup],['POSEBNE NAPOMENE',DATA.rules.special]];return shell(`<section class="page-head"><h1>PRAVILA & NAGRADE</h1><p>Over Under Fantasy Liga · ${DATA.meta.season}</p></section><div class="grid rules-grid">${blocks.map(([t,arr])=>`<section class="card"><h3>${t}</h3><ul>${arr.map(x=>`<li>${x}</li>`).join('')}</ul></section>`).join('')}<section class="card"><h3>NAGRADE</h3><div class="prizes">${DATA.prizes.map((p,i)=>`<div class="prize"><div class="medal">${i+1}</div><div><b>${p.title}</b><div>${p.text}</div></div></div>`).join('')}</div></section></div><div class="notice">Napomena: datum žurke u dostavljenom dokumentu je 24.04.2024. i ostavljen je kao stavka za proveru.</div>`,'rules');}
function render(){const r=route(),fn={home,league,cup,double:doublePage,budget,record,rules}[r]||home;document.getElementById('app').innerHTML=fn();initNav();window.scrollTo(0,0)}window.addEventListener('hashchange',render);render();
